#include "globali.h"

void InitGlobali()
{
	globali.n_tipi = 0;
	globali.tipi = NULL;

	globali.sample.HL = NULL;
	globali.sample.q = NULL;
	globali.sample.x = NULL;
	globali.sample.y = NULL;

	globali.cluster_coeff.tmpm_i = NULL;
	globali.cluster_coeff.ind = NULL;
	globali.cluster_coeff.neighbours = NULL;

	globali.assign_nodes.Sin_h = NULL;
	globali.assign_nodes.tmp_i = NULL;
	globali.assign_nodes.tmp_d = NULL;
	globali.assign_nodes.or_h = NULL;
	globali.assign_nodes.aus_h = NULL;
	globali.assign_nodes.M_in = NULL;
	globali.assign_nodes.Ord = NULL;
	globali.assign_nodes.p = NULL;
	globali.assign_nodes.ind_h = NULL;
	globali.assign_nodes.ri = NULL;
	globali.assign_nodes.co = NULL;
	globali.assign_nodes.ind = NULL;
	globali.assign_nodes.index = NULL;

	globali.pathlength.dist_tot = NULL;
	globali.pathlength.new_neighbours = NULL;
	globali.pathlength.distanza = NULL;
	globali.pathlength.visitati = NULL;
	globali.pathlength.neighbours = NULL;
	globali.pathlength.tmp1_i = NULL;
	globali.pathlength.tmpm_i = NULL;

	globali.hubs.S = NULL;
	globali.hubs.P = NULL;
	globali.hubs.ind = NULL;
	globali.hubs.ind2 = NULL;
	globali.hubs.tmp1_i = NULL;
	globali.hubs.tmp1_d = NULL;
	globali.hubs.Hio = NULL;
	globali.hubs.H = NULL;
	globali.hubs.pl = NULL;

	globali.scoremodular.tmpm_d = NULL;
	globali.scoremodular.scalare_d = NULL;
	globali.scoremodular.S_new = NULL;
	globali.scoremodular.tmp_i1 = NULL;
	globali.scoremodular.tmp1_d = NULL;
	globali.scoremodular.T1 = NULL;
	globali.scoremodular.T2 = NULL;
	globali.scoremodular.old1 = NULL;
	globali.scoremodular.old2 = NULL;
	globali.scoremodular.new1 = NULL;
	globali.scoremodular.new2 = NULL;
	globali.scoremodular.toll1 = NULL;
	globali.scoremodular.toll2 = NULL;
	globali.scoremodular.a = NULL;
	globali.scoremodular.b = NULL;
	globali.scoremodular.ind = NULL;
	globali.scoremodular.m = NULL;
	globali.scoremodular.S1 = NULL;
	globali.scoremodular.S2 = NULL;
	globali.scoremodular.ind1 = NULL;
	globali.scoremodular.ind2 = NULL;
	globali.scoremodular.indinf = NULL;

	globali.connetti_scalefree.ind_out = NULL;
	globali.connetti_scalefree.co_out = NULL;
	globali.connetti_scalefree.Sc2_out = NULL;
	globali.connetti_scalefree.Sc2_in = NULL;
	globali.connetti_scalefree.toll = NULL;
	globali.connetti_scalefree.Sc1_out = NULL;
	globali.connetti_scalefree.non_connessi = NULL;
	globali.connetti_scalefree.p_out = NULL;
	globali.connetti_scalefree.Sc1_in = NULL;
	globali.connetti_scalefree.co_in = NULL;
	globali.connetti_scalefree.Freq_in = NULL;
	globali.connetti_scalefree.Freq_in1 = NULL;
	globali.connetti_scalefree.Sc_out = NULL;
	globali.connetti_scalefree.ind_in = NULL;
	globali.connetti_scalefree.Freq_out = NULL;
	globali.connetti_scalefree.Freq_out1 = NULL;
	globali.connetti_scalefree.Sin = NULL;
	globali.connetti_scalefree.Sout = NULL;
	globali.connetti_scalefree.tmp1_i = NULL;
	globali.connetti_scalefree.tmp2_i = NULL;
	globali.connetti_scalefree.tmp1_d = NULL;
	globali.connetti_scalefree.connessi = NULL;
	globali.connetti_scalefree.nonco_out = NULL;
	globali.connetti_scalefree.p = NULL;
	globali.connetti_scalefree.p_in = NULL;
	globali.connetti_scalefree.Sc_in = NULL;
	globali.connetti_scalefree.nonco_in = NULL;

	globali.check_conn.Mt = NULL;
	globali.check_conn.Maus = NULL;
	globali.check_conn.tmp_i = NULL;
	globali.check_conn.colore = NULL;
	globali.check_conn.grigi = NULL;
	globali.check_conn.ind = NULL;
	globali.check_conn.adj = NULL;
	globali.check_conn.tmp1_d = NULL;
	globali.check_conn.scalare_i = NULL;
	globali.check_conn.scalare_d = NULL;

	globali.HMM.Sr = NULL;
	globali.HMM.Sin = NULL;
	globali.HMM.Sout = NULL;
	globali.HMM.hubs = NULL;
	globali.HMM.ind_Sc = NULL;
	globali.HMM.LG = NULL;
	globali.HMM.ind = NULL;
	globali.HMM.ind_s = NULL;
	globali.HMM.indm = NULL;
	globali.HMM.CCs = NULL;
	globali.HMM.non_connessi = NULL;
	globali.HMM.h = NULL;
	globali.HMM.indp = NULL;
	globali.HMM.h_new = NULL;
	globali.HMM.m = NULL;
	globali.HMM.MC = NULL;
	globali.HMM.tmp1_i = NULL;
	globali.HMM.scalare_i = NULL;
	globali.HMM.CC = NULL;
	globali.HMM.FB = NULL;
	globali.HMM.segno = NULL;
	globali.HMM.h1 = NULL;
	globali.HMM.h_new1 = NULL;
	globali.HMM.tmp2_i = NULL;
	globali.HMM.dim = NULL;
	globali.HMM.mod_type = NULL;
	globali.HMM.a1 = NULL;
	globali.HMM.a2 = NULL;
	globali.HMM.toll = NULL;
	globali.HMM.prior_p_subnet = NULL;
	globali.HMM.Freq_in = NULL;
	globali.HMM.Freq_out = NULL;
	globali.HMM.tmp1_d = NULL;
	globali.HMM.tmp2_d = NULL;
	globali.HMM.scalare_d = NULL;
	globali.HMM.scalare1_d = NULL;
	globali.HMM.Prob = NULL;
	globali.HMM.STin = NULL;
	globali.HMM.STout = NULL;
	globali.HMM.p = NULL;
	globali.HMM.dist = NULL;
	globali.HMM.CCp = NULL;
	globali.HMM.ppp = NULL;
	globali.HMM.ris_cc = NULL;
	globali.HMM.Sc_vett = NULL;
	globali.HMM.pm = NULL;
	globali.HMM.prob_mod = NULL;
	globali.HMM.p_out = NULL;
	globali.HMM.M = NULL;
	globali.HMM.mod1 = NULL;
	globali.HMM.mod2 = NULL;
	globali.HMM.mod3 = NULL;
	globali.HMM.tmpm_i = NULL;
	globali.HMM.aus = NULL;
	globali.HMM.Sc1 = NULL;
	globali.HMM.Sc2 = NULL;
	globali.HMM.Sc3 = NULL;
	globali.HMM.Sc = NULL;
	globali.HMM.LC = 0;
	globali.HMM.CCind = NULL;

	globali.probmod.S_out = NULL;
	globali.probmod.S_in = NULL;
	globali.probmod.Sc = NULL;
	globali.probmod.checkIN = NULL;
	globali.probmod.checkOUT = NULL;
	globali.probmod.memory = NULL;
	globali.probmod.M_in = NULL;
	globali.probmod.M_out = NULL;
	globali.probmod.tmp_i1 = NULL;
	globali.probmod.tmp_i2 = NULL;
	globali.probmod.tmp_i3 = NULL;
	globali.probmod.indInf = NULL;
	globali.probmod.I = NULL;
	globali.probmod.ord_ind = NULL;
	globali.probmod.rs = NULL;
	globali.probmod.ind1 = NULL;
	globali.probmod.scalare_i = NULL;
	globali.probmod.I_add = NULL;
	globali.probmod.tmp_d1 = NULL;
	globali.probmod.score_matr1 = NULL;
	globali.probmod.score_matr2 = NULL;
	globali.probmod.score_matr3 = NULL;

	globali.HMM_und.Sr = NULL;
	globali.HMM_und.Sin = NULL;
	globali.HMM_und.Sout = NULL;
	globali.HMM_und.hubs = NULL;
	globali.HMM_und.ind_Sc = NULL;
	globali.HMM_und.LG = NULL;
	globali.HMM_und.ind = NULL;
	globali.HMM_und.ind_s = NULL;
	globali.HMM_und.indm = NULL;
	globali.HMM_und.CCs = NULL;
	globali.HMM_und.non_connessi = NULL;
	globali.HMM_und.h = NULL;
	globali.HMM_und.indp = NULL;
	globali.HMM_und.h_new = NULL;
	globali.HMM_und.m = NULL;
	globali.HMM_und.MC = NULL;
	globali.HMM_und.tmp1_i = NULL;
	globali.HMM_und.scalare_i = NULL;
	globali.HMM_und.CC = NULL;
	globali.HMM_und.FB = NULL;
	globali.HMM_und.segno = NULL;
	globali.HMM_und.h1 = NULL;
	globali.HMM_und.h_new1 = NULL;
	globali.HMM_und.tmp2_i = NULL;
	globali.HMM_und.dim = NULL;
	globali.HMM_und.mod_type = NULL;
	globali.HMM_und.a1 = NULL;
	globali.HMM_und.a2 = NULL;
	globali.HMM_und.SIMM = NULL;
	globali.HMM_und.toll = NULL;
	globali.HMM_und.prior_p_subnet = NULL;
	globali.HMM_und.Freq_in = NULL;
	globali.HMM_und.Freq_out = NULL;
	globali.HMM_und.tmp1_d = NULL;
	globali.HMM_und.tmp2_d = NULL;
	globali.HMM_und.scalare_d = NULL;
	globali.HMM_und.scalare1_d = NULL;
	globali.HMM_und.Prob = NULL;
	globali.HMM_und.STin = NULL;
	globali.HMM_und.STout = NULL;
	globali.HMM_und.p = NULL;
	globali.HMM_und.dist = NULL;
	globali.HMM_und.CCp = NULL;
	globali.HMM_und.ppp = NULL;
	globali.HMM_und.ris_cc = NULL;
	globali.HMM_und.Sc_vett = NULL;
	globali.HMM_und.pm = NULL;
	globali.HMM_und.prob_mod = NULL;
	globali.HMM_und.p_out = NULL;
	globali.HMM_und.M = NULL;
	globali.HMM_und.mod1 = NULL;
	globali.HMM_und.mod2 = NULL;
	globali.HMM_und.mod3 = NULL;
	globali.HMM_und.tmpm_i = NULL;
	globali.HMM_und.aus = NULL;
	globali.HMM_und.Sc1 = NULL;
	globali.HMM_und.Sc2 = NULL;
	globali.HMM_und.Sc3 = NULL;
	globali.HMM_und.Sc = NULL;
	globali.HMM_und.LC = 0;
	globali.HMM_und.CCind = NULL;

	globali.assign_nodes_und.Sout_h = NULL;
	globali.assign_nodes_und.tmp_i = NULL;
	globali.assign_nodes_und.tmp_d = NULL;
	globali.assign_nodes_und.or_h = NULL;
	globali.assign_nodes_und.aus_h = NULL;
	globali.assign_nodes_und.M_out = NULL;
	globali.assign_nodes_und.Ord = NULL;
	globali.assign_nodes_und.p = NULL;
	globali.assign_nodes_und.ind_h = NULL;
	globali.assign_nodes_und.ri = NULL;
	globali.assign_nodes_und.co = NULL;
	globali.assign_nodes_und.ind = NULL;
	globali.assign_nodes_und.index = NULL;

	globali.probmod_und.S_out = NULL;
	globali.probmod_und.Sc = NULL;
	globali.probmod_und.scalare_d = NULL;
	globali.probmod_und.checkIN = NULL;
	globali.probmod_und.checkOUT = NULL;
	globali.probmod_und.memory = NULL;
	globali.probmod_und.M_in = NULL;
	globali.probmod_und.M_out = NULL;
	globali.probmod_und.tmp_i1 = NULL;
	globali.probmod_und.tmp_i2 = NULL;
	globali.probmod_und.indok = NULL;
	globali.probmod_und.indInf = NULL;
	globali.probmod_und.I = NULL;
	globali.probmod_und.ord_ind = NULL;
	globali.probmod_und.aus = NULL;
	globali.probmod_und.rs = NULL;
	globali.probmod_und.ind1 = NULL;
	globali.probmod_und.scalare_i = NULL;
	globali.probmod_und.I_add = NULL;
	globali.probmod_und.tmp_d1 = NULL;

}

void CancGlobali()
{
	int i;

	libera(globali.tipi);

	CANCELLAv_i(globali.sample.HL);
	CANCELLAv_d(globali.sample.q);
	CANCELLAv_i(globali.sample.x);
	CANCELLAv_i(globali.sample.y);

	CANCELLAm_i(globali.cluster_coeff.tmpm_i);
	CANCELLAv_i(globali.cluster_coeff.ind);
	CANCELLAv_i(globali.cluster_coeff.neighbours);

	CANCELLAv_i(globali.assign_nodes.Sin_h);
	CANCELLAv_i(globali.assign_nodes.tmp_i);
	CANCELLAv_d(globali.assign_nodes.tmp_d);
	CANCELLAv_i(globali.assign_nodes.or_h);
	CANCELLAv_i(globali.assign_nodes.aus_h);
	CANCELLAv_i(globali.assign_nodes.M_in);
	CANCELLAv_i(globali.assign_nodes.Ord);
	CANCELLAv_d(globali.assign_nodes.p);
	CANCELLAv_i(globali.assign_nodes.ind_h);
	CANCELLAv_i(globali.assign_nodes.ri);
	CANCELLAv_i(globali.assign_nodes.co);
	CANCELLAv_i(globali.assign_nodes.ind);
	CANCELLAv_i(globali.assign_nodes.index);

	CANCELLAv_i(globali.pathlength.dist_tot);
	CANCELLAv_i(globali.pathlength.new_neighbours);
	CANCELLAv_d(globali.pathlength.distanza);
	CANCELLAv_i(globali.pathlength.visitati);
	CANCELLAv_i(globali.pathlength.neighbours);
	CANCELLAv_i(globali.pathlength.tmp1_i);
	CANCELLAm_i(globali.pathlength.tmpm_i);

	CANCELLAv_i(globali.hubs.S);
	CANCELLAv_d(globali.hubs.P);
	CANCELLAv_i(globali.hubs.ind);
	CANCELLAv_i(globali.hubs.ind2);
	CANCELLAv_i(globali.hubs.tmp1_i);
	CANCELLAv_d(globali.hubs.tmp1_d);
	CANCELLAv_i(globali.hubs.Hio);
	CANCELLAv_i(globali.hubs.H);
	CANCELLAm_d(globali.hubs.pl);

	CANCELLAm_d(globali.scoremodular.tmpm_d);
	CANCELLAv_d(globali.scoremodular.scalare_d);
	CANCELLAv_i(globali.scoremodular.S_new);
	CANCELLAv_i(globali.scoremodular.tmp_i1);
	CANCELLAv_d(globali.scoremodular.tmp1_d);
	CANCELLAv_d(globali.scoremodular.T1);
	CANCELLAv_d(globali.scoremodular.T2);
	CANCELLAv_d(globali.scoremodular.old1);
	CANCELLAv_d(globali.scoremodular.old2);
	CANCELLAv_d(globali.scoremodular.new1);
	CANCELLAv_d(globali.scoremodular.new2);
	CANCELLAv_d(globali.scoremodular.toll1);
	CANCELLAv_d(globali.scoremodular.toll2);
	CANCELLAv_d(globali.scoremodular.a);
	CANCELLAv_d(globali.scoremodular.b);
	CANCELLAv_i(globali.scoremodular.ind);
	CANCELLAv_d(globali.scoremodular.m);
	CANCELLAv_d(globali.scoremodular.S1);
	CANCELLAv_d(globali.scoremodular.S2);
	CANCELLAv_i(globali.scoremodular.ind1);
	CANCELLAv_i(globali.scoremodular.ind2);
	CANCELLAv_i(globali.scoremodular.indinf);

	CANCELLAv_i(globali.connetti_scalefree.ind_out);
	CANCELLAv_i(globali.connetti_scalefree.co_out);
	CANCELLAv_d(globali.connetti_scalefree.Sc2_out);
	CANCELLAv_d(globali.connetti_scalefree.Sc2_in);
	CANCELLAv_d(globali.connetti_scalefree.toll);
	CANCELLAv_d(globali.connetti_scalefree.Sc1_out);
	CANCELLAv_i(globali.connetti_scalefree.non_connessi);
	CANCELLAv_d(globali.connetti_scalefree.p_out);
	CANCELLAv_d(globali.connetti_scalefree.Sc1_in);
	CANCELLAv_i(globali.connetti_scalefree.co_in);
	CANCELLAv_d(globali.connetti_scalefree.Freq_in);
	CANCELLAv_i(globali.connetti_scalefree.Freq_in1);
	CANCELLAv_d(globali.connetti_scalefree.Sc_out);
	CANCELLAv_i(globali.connetti_scalefree.ind_in);
	CANCELLAv_d(globali.connetti_scalefree.Freq_out);
	CANCELLAv_i(globali.connetti_scalefree.Freq_out1);
	CANCELLAv_i(globali.connetti_scalefree.Sin);
	CANCELLAv_i(globali.connetti_scalefree.Sout);
	CANCELLAv_i(globali.connetti_scalefree.tmp1_i);
	CANCELLAv_i(globali.connetti_scalefree.tmp2_i);
	CANCELLAv_d(globali.connetti_scalefree.tmp1_d);
	CANCELLAv_i(globali.connetti_scalefree.connessi);
	CANCELLAv_i(globali.connetti_scalefree.nonco_out);
	CANCELLAv_d(globali.connetti_scalefree.p);
	CANCELLAv_d(globali.connetti_scalefree.p_in);
	CANCELLAv_d(globali.connetti_scalefree.Sc_in);
	CANCELLAv_i(globali.connetti_scalefree.nonco_in);

	CANCELLAm_i(globali.check_conn.Mt);
	CANCELLAm_i(globali.check_conn.Maus);
	CANCELLAv_i(globali.check_conn.tmp_i);
	CANCELLAv_i(globali.check_conn.colore);
	CANCELLAv_i(globali.check_conn.grigi);
	CANCELLAv_i(globali.check_conn.ind);
	CANCELLAv_i(globali.check_conn.adj);
	CANCELLAv_d(globali.check_conn.tmp1_d);
	CANCELLAv_i(globali.check_conn.scalare_i);
	CANCELLAv_d(globali.check_conn.scalare_d);

	CANCELLAv_i(globali.HMM.Sr);
	CANCELLAv_i(globali.HMM.Sin);
	CANCELLAv_i(globali.HMM.Sout);
	CANCELLAv_i(globali.HMM.hubs);
	CANCELLAv_i(globali.HMM.ind_Sc);
	CANCELLAv_i(globali.HMM.LG);
	CANCELLAv_i(globali.HMM.ind);
	CANCELLAv_i(globali.HMM.ind_s);
	CANCELLAv_i(globali.HMM.indm);
	CANCELLAv_i(globali.HMM.CCs);
	CANCELLAv_i(globali.HMM.non_connessi);
	CANCELLAv_i(globali.HMM.h);
	CANCELLAv_i(globali.HMM.indp);
	CANCELLAv_i(globali.HMM.h_new);
	CANCELLAv_i(globali.HMM.m);
	CANCELLAv_i(globali.HMM.MC);
	CANCELLAv_i(globali.HMM.tmp1_i);
	CANCELLAv_i(globali.HMM.scalare_i);
	CANCELLAv_i(globali.HMM.CC);
	CANCELLAv_i(globali.HMM.FB);
	CANCELLAv_i(globali.HMM.segno);
	CANCELLAv_i(globali.HMM.h1);
	CANCELLAv_i(globali.HMM.h_new1);
	CANCELLAv_i(globali.HMM.tmp2_i);
	CANCELLAv_i(globali.HMM.dim);
	CANCELLAv_i(globali.HMM.mod_type);
	CANCELLAv_i(globali.HMM.a1);
	CANCELLAv_i(globali.HMM.a2);
	CANCELLAv_d(globali.HMM.toll);
	CANCELLAv_d(globali.HMM.prior_p_subnet);
	CANCELLAv_d(globali.HMM.Freq_in);
	CANCELLAv_d(globali.HMM.Freq_out);
	CANCELLAv_d(globali.HMM.tmp1_d);
	CANCELLAv_d(globali.HMM.tmp2_d);
	CANCELLAv_d(globali.HMM.scalare_d);
	CANCELLAv_d(globali.HMM.scalare1_d);
	CANCELLAv_d(globali.HMM.Prob);
	CANCELLAv_d(globali.HMM.STin);
	CANCELLAv_d(globali.HMM.STout);
	CANCELLAv_d(globali.HMM.p);
	CANCELLAv_d(globali.HMM.dist);
	CANCELLAv_d(globali.HMM.CCp);
	CANCELLAv_d(globali.HMM.ppp);
	CANCELLAv_d(globali.HMM.ris_cc);
	CANCELLAv_d(globali.HMM.Sc_vett);
	CANCELLAv_d(globali.HMM.pm);
	CANCELLAv_d(globali.HMM.prob_mod);
	CANCELLAv_d(globali.HMM.p_out);
	CANCELLAm_i(globali.HMM.M);
	CANCELLAm_i(globali.HMM.mod1);
	CANCELLAm_i(globali.HMM.mod2);
	CANCELLAm_i(globali.HMM.mod3);
	CANCELLAm_i(globali.HMM.tmpm_i);
	CANCELLAm_d(globali.HMM.aus);
	CANCELLAm_d(globali.HMM.Sc1);
	CANCELLAm_d(globali.HMM.Sc2);
	CANCELLAm_d(globali.HMM.Sc3);
	CANCELLAm_d(globali.HMM.Sc);

	for (i = 0; i < globali.HMM.LC; i++)
		CANCELLAv_i(globali.HMM.CCind[i]);

	libera(globali.HMM.CCind);

	CANCELLAv_d(globali.probmod.S_out);
	CANCELLAv_d(globali.probmod.S_in);
	CANCELLAm_d(globali.probmod.score_matr1);
	CANCELLAm_d(globali.probmod.score_matr2);
	CANCELLAm_d(globali.probmod.score_matr3);
	CANCELLAm_i(globali.probmod.checkIN);
	CANCELLAm_i(globali.probmod.checkOUT);
	CANCELLAm_i(globali.probmod.memory);
	CANCELLAv_i(globali.probmod.M_in);
	CANCELLAv_i(globali.probmod.M_out);
	CANCELLAv_i(globali.probmod.tmp_i1);
	CANCELLAv_i(globali.probmod.tmp_i2);
	CANCELLAv_i(globali.probmod.tmp_i3);
	CANCELLAv_i(globali.probmod.indInf);
	CANCELLAv_i(globali.probmod.I);
	CANCELLAv_i(globali.probmod.ord_ind);
	CANCELLAv_i(globali.probmod.rs);
	CANCELLAv_i(globali.probmod.ind1);
	CANCELLAv_i(globali.probmod.scalare_i);
	CANCELLAv_i(globali.probmod.I_add);
	CANCELLAv_d(globali.probmod.tmp_d1);

	CANCELLAv_i(globali.HMM_und.Sr);
	CANCELLAv_i(globali.HMM_und.Sin);
	CANCELLAv_i(globali.HMM_und.Sout);
	CANCELLAv_i(globali.HMM_und.hubs);
	CANCELLAv_i(globali.HMM_und.ind_Sc);
	CANCELLAv_i(globali.HMM_und.LG);
	CANCELLAv_i(globali.HMM_und.ind);
	CANCELLAv_i(globali.HMM_und.ind_s);
	CANCELLAv_i(globali.HMM_und.indm);
	CANCELLAv_i(globali.HMM_und.CCs);
	CANCELLAv_i(globali.HMM_und.non_connessi);
	CANCELLAv_i(globali.HMM_und.h);
	CANCELLAv_i(globali.HMM_und.indp);
	CANCELLAv_i(globali.HMM_und.h_new);
	CANCELLAv_i(globali.HMM_und.m);
	CANCELLAv_i(globali.HMM_und.MC);
	CANCELLAv_i(globali.HMM_und.tmp1_i);
	CANCELLAv_i(globali.HMM_und.scalare_i);
	CANCELLAv_i(globali.HMM_und.CC);
	CANCELLAv_i(globali.HMM_und.FB);
	CANCELLAv_i(globali.HMM_und.segno);
	CANCELLAv_i(globali.HMM_und.h1);
	CANCELLAv_i(globali.HMM_und.h_new1);
	CANCELLAv_i(globali.HMM_und.tmp2_i);
	CANCELLAv_i(globali.HMM_und.dim);
	CANCELLAv_i(globali.HMM_und.mod_type);
	CANCELLAv_i(globali.HMM_und.a1);
	CANCELLAv_i(globali.HMM_und.a2);
	CANCELLAv_i(globali.HMM_und.SIMM);
	CANCELLAv_d(globali.HMM_und.toll);
	CANCELLAv_d(globali.HMM_und.prior_p_subnet);
	CANCELLAv_d(globali.HMM_und.Freq_in);
	CANCELLAv_d(globali.HMM_und.Freq_out);
	CANCELLAv_d(globali.HMM_und.tmp1_d);
	CANCELLAv_d(globali.HMM_und.tmp2_d);
	CANCELLAv_d(globali.HMM_und.scalare_d);
	CANCELLAv_d(globali.HMM_und.scalare1_d);
	CANCELLAv_d(globali.HMM_und.Prob);
	CANCELLAv_d(globali.HMM_und.STin);
	CANCELLAv_d(globali.HMM_und.STout);
	CANCELLAv_d(globali.HMM_und.p);
	CANCELLAv_d(globali.HMM_und.dist);
	CANCELLAv_d(globali.HMM_und.CCp);
	CANCELLAv_d(globali.HMM_und.ppp);
	CANCELLAv_d(globali.HMM_und.ris_cc);
	CANCELLAv_d(globali.HMM_und.Sc_vett);
	CANCELLAv_d(globali.HMM_und.pm);
	CANCELLAv_d(globali.HMM_und.prob_mod);
	CANCELLAv_d(globali.HMM_und.p_out);
	CANCELLAm_i(globali.HMM_und.M);
	CANCELLAm_i(globali.HMM_und.mod1);
	CANCELLAm_i(globali.HMM_und.mod2);
	CANCELLAm_i(globali.HMM_und.mod3);
	CANCELLAm_i(globali.HMM_und.tmpm_i);
	CANCELLAm_d(globali.HMM_und.aus);
	CANCELLAm_d(globali.HMM_und.Sc1);
	CANCELLAm_d(globali.HMM_und.Sc2);
	CANCELLAm_d(globali.HMM_und.Sc3);
	CANCELLAm_d(globali.HMM_und.Sc);

	for (i = 0; i < globali.HMM_und.LC; i++)
		CANCELLAv_i(globali.HMM_und.CCind[i]);
	libera(globali.HMM_und.CCind);

	CANCELLAv_i(globali.assign_nodes_und.Sout_h);
	CANCELLAv_i(globali.assign_nodes_und.tmp_i);
	CANCELLAv_d(globali.assign_nodes_und.tmp_d);
	CANCELLAv_i(globali.assign_nodes_und.or_h);
	CANCELLAv_i(globali.assign_nodes_und.aus_h);
	CANCELLAv_i(globali.assign_nodes_und.M_out);
	CANCELLAv_i(globali.assign_nodes_und.Ord);
	CANCELLAv_d(globali.assign_nodes_und.p);
	CANCELLAv_i(globali.assign_nodes_und.ind_h);
	CANCELLAv_i(globali.assign_nodes_und.ri);
	CANCELLAv_i(globali.assign_nodes_und.co);
	CANCELLAv_i(globali.assign_nodes_und.ind);
	CANCELLAv_i(globali.assign_nodes_und.index);

	CANCELLAv_d(globali.probmod_und.S_out);
	CANCELLAm_d(globali.probmod_und.Sc);
	CANCELLAv_d(globali.probmod_und.scalare_d);
	CANCELLAm_i(globali.probmod_und.checkIN);
	CANCELLAm_i(globali.probmod_und.checkOUT);
	CANCELLAm_i(globali.probmod_und.memory);
	CANCELLAv_i(globali.probmod_und.M_in);
	CANCELLAv_i(globali.probmod_und.M_out);
	CANCELLAv_i(globali.probmod_und.tmp_i1);
	CANCELLAv_i(globali.probmod_und.tmp_i2);
	CANCELLAv_i(globali.probmod_und.indok);
	CANCELLAv_i(globali.probmod_und.indInf);
	CANCELLAv_i(globali.probmod_und.I);
	CANCELLAv_i(globali.probmod_und.ord_ind);
	CANCELLAv_i(globali.probmod_und.aus);
	CANCELLAv_i(globali.probmod_und.rs);
	CANCELLAv_i(globali.probmod_und.ind1);
	CANCELLAv_i(globali.probmod_und.scalare_i);
	CANCELLAv_i(globali.probmod_und.I_add);
	CANCELLAv_d(globali.probmod_und.tmp_d1);
}
