library("netsim")

cat("\n*** simulatenet ***\n\n")
cat("act.fun ...\n")
ris <- simulatenet(N=5, act.fun="linear", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("f.pr.and ...\n")
ris <- simulatenet(N=5, f.pr.and="1 / (1 + e ^ (-10 * (x - 0.5)))", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("geometric ...\n")
ris <- simulatenet(N=5, connectivity="geometric", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("itera & save ...\n")
ris <- simulatenet(N=50, save=TRUE, itera=5, times=seq(1,10))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("MTM ...\n")
ris <- simulatenet(N=5, connectivity="MTM", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("ODE ...\n")
ris <- simulatenet(N=5, method="rkf45", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("INdregree ...\n")
ris <- simulatenet(N=5, INdegree="out", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("random ...\n")
ris <- simulatenet(N=5, connectivity="random", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("save ...\n")
ris <- simulatenet(N=5, save=TRUE, times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("scale free ...\n")
ris <- simulatenet(N=5, connectivity="scale free", times=seq(1,5))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("parameter Xmin external ...\n")
ris <- simulatenet(N=5, connectivity="scale free", method="rkf45", Xmin=rep(0,5), params=c(2,2,2,0,0,1))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("parameter Xmin uniform ...\n")
ris <- simulatenet(N=5, connectivity="scale free", method="rkf45", params=c(2,2,2,0,1,1))
cat("ok\n\n")
cat("-----------------------------------\n")
#~ cat("1000 genes ...\n")
#~ ris1000 <- simulatenet(N=1000, connectivity="scale free", times=seq(1,5))
#~ cat("ok\n\n")
#~ cat("-----------------------------------\n")
cat("-----------------------------------\n")
cat("\n*** simulateprofiles ***\n\n")

Dati <- matrix(c(1.793561,1.793561,1.793561,1.793561,1.793561,4.239327,4.239327,4.239327,4.239327,4.239327,1.031338,1.031338,1.031338,1.031338,1.031338,1.789676,1.789676,1.789676,1.789676,1.789676,7.767749,7.767749,7.767749,7.767749,7.767749), 5, 5)

weights <- matrix(c(0,0,0,-1,0,-1,0,-1,0,0,0,-1,0,0,-1,-1,0,0,0,0,0,0,-1,0,0), 5, 5)

lambda <-c(1.1056752,0.9747519,1.0007163,1.0061211,1.1354204)

alpha <- c(9.869912,9.955962,10.056057,9.922354,9.950865)

rules <- list(c(5), c(5), c(5), c(5), c(1))

beta <- c(0.4934634,0.4930697,0.4926102,0.4976155,0.4905647)

N<-dim(Dati)[1]
times<-seq(1,5)

cat("rules as list ...\n")
ris <- simulateprofiles(weights=weights, Rules=rules, lambda=lambda, alpha=alpha, beta=beta, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("act.fun ...\n")
ris <- simulateprofiles(weights=weights, Rules=rules, act.fun="linear", times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("ext.fun ...\n")
ext.W<-matrix(0, N, 2)
ext.W[2,1]<-ext.W[3,1]<-ext.W[2,2]<-1
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, EXT.IN=ext.W, EXT.FUN=list("sin(x)", "if(x < 1, 0, x - 1)"), times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("f.pr.and ...\n")
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, f.pr.and="1 / (1 + e ^ (-10 * (x - 0.5)))", times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("itera & save ...\n")
#~ ris <- simulateprofiles(weights=weights, itera=10, save=TRUE, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("all KO in turn ...\n")
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, ko.experim=c(0), times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("some KO ...\n")
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, ko.experim=c(1,3,5), save=TRUE, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("ODE ...\n")
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, method="rkf45", times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("random rules ...\n")
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("save ...\n")
ris <- simulateprofiles(weights=weights, lambda=lambda, alpha=alpha, beta=beta, save=TRUE, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("da SN ...\n")
net<-simulatenet(10, connectivity="geometric", save=TRUE, itera=5)
ris <- simulateprofiles(weights=NULL, method="rkf45", params=c(4,4,4,4,4,4), itera=5, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("drom SN with SN rules ...\n")
ris <- simulateprofiles(weights=NULL, Rules=NULL, method="rkf45", params=c(4,4,4,4,4,4), itera=5, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
cat("from SN with KO ...\n")
ris <- simulateprofiles(weights=NULL, method="rkf45", ko.experim=c(1,3,5), params=c(4,4,4,4,4,4), itera=5, times=times)
cat("ok\n\n")
cat("-----------------------------------\n")
#~ cat("1000 genes ...\n")
#~ ris <- simulateprofiles(weights=ris1000[[1]][[2]], method="rkf45", times=times)
#~ cat("ok\n\n")
#~ cat("-----------------------------------\n")
cat("parameter Xmin external ...\n")
ris <- simulateprofiles(weights=weights, Rules=rules, act.fun="linear", times=times, Xmin=rep(0,5), params=c(2,2,2,0,0,1))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("parameter Xmin uniform ...\n")
ris <- simulateprofiles(weights=weights, Rules=rules, act.fun="linear", times=times, params=c(2,2,2,0,1,1))
cat("ok\n\n")
cat("-----------------------------------\n")
cat("ALL TESTS PASSED SUCCESSFULLY\n")